# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: build job 
    pool:
     vmImage: 'ubuntu-latest'
    steps:
    # task-1 Build docker image and push to azure acr
    - task: Docker@2
      inputs:
        containerRegistry: 'manual-aksdevopsacr-svc'
        repository: 'custom2aksnginxapp1'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 
         $(tag)

    - bash: echo files in the default working directory ; ls -R $(System.DefaultWorkingDirectory)
    - bash: echo files in the artifacts directory before push; ls -R $(Build.ArtifactStagingDirectory)
    # task-2 : copy files (copy files from source directory to target folde)
    # source directory: $(System.DefaultWorkingDirectory)/kube-manifasts
    #target directory: $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true
    # task-3 : Publish build artifacts (publish to build artifacts)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'